export const networks = Object.freeze({
  polkadot: "polkadot",
  kusama: "kusama",
  statemine: "statemine",
  statemint: "statemint",
  karura: "karura",
  khala: "khala",
  phala: "phala",
  bifrost: "bifrost", // bifrost is bifrost-kusama
  bifrostPolkadot: "bifrost-polkadot",
  polkadex: "polkadex",
  moonbeam: "moonbeam",
  moonriver: "moonriver",
  acala: "acala",
  astar: "astar",
  astarEvm: "astar_evm",
  turing: "turing",
  crab: "crab",
  darwinia: "darwinia",
  ethereum: "ethereum",
  litmus: "litmus",
  litentry: "litentry",
  shiden: "shiden",
  altair: "altair",
  parallel: "parallel",
  hydradx: "hydradx",
  hydration: "hydration",
  rococo: "rococo",
  creditcoin: "creditcoin",
  creditcoinEvm: "creditcoin_evm",
  creditcoinNative: "creditcoin_native",
});
